// @generated by scripts/generate-runtime-contracts.mjs. DO NOT EDIT.
// schema-sha256: 1ac359c44b07684f2e93a3634d0ef3fa724ba1559b4fdb6849f5c18795da60b0

export const RUNTIME_SCHEMA_VERSION = '2.0.0' as const;
export const RUNTIME_PROTOCOL_VERSION = { major: 2, minor: 0, patch: 0 } as const;
export const RUNTIME_SCHEMA_SHA256 = '1ac359c44b07684f2e93a3634d0ef3fa724ba1559b4fdb6849f5c18795da60b0' as const;

export const RUNTIME_REQUEST_TYPES = ["initialize","capabilityNegotiation","sessionList","sessionCreate","sessionResume","sessionClose","sessionFork","prompt","cancel","approval","memory","workspace","usageQuery"] as const;
export const RUNTIME_EVENT_TYPES = ["contentDelta","toolProposed","toolStatus","toolResult","approvalRequested","approvalResolved","cancelled","error","memoryContext","contextCompressed","checkpoint","usage","finished"] as const;

export const RUNTIME_REQUEST_REQUIRED_FIELDS = {"initialize":["type","clientVersion","supportedProtocolVersions","capabilities"],"capabilityNegotiation":["type","capabilities"],"sessionList":["type"],"sessionCreate":["type"],"sessionResume":["type","targetSessionId"],"sessionClose":["type","targetSessionId"],"sessionFork":["type","targetSessionId"],"prompt":["type","content","stream"],"cancel":["type"],"approval":["type","approvalId","decision"],"memory":["type","operation"],"workspace":["type","operation"],"usageQuery":["type","scope"]} as const;
export const RUNTIME_EVENT_REQUIRED_FIELDS = {"contentDelta":["type","delta"],"toolProposed":["type","toolCallId","toolName","arguments"],"toolStatus":["type","toolCallId","status"],"toolResult":["type","toolCallId","status","result"],"approvalRequested":["type","approvalId","message"],"approvalResolved":["type","approvalId","decision"],"cancelled":["type"],"error":["type","error"],"memoryContext":["type","items"],"contextCompressed":["type","beforeTokens","afterTokens"],"checkpoint":["type","checkpointId"],"usage":["type","inputTokens","outputTokens"],"finished":["type","reason"]} as const;

export const ACTOR_VALUES = ["user","assistant","system","tool","runtime"] as const;
export const APPROVAL_DECISION_VALUES = ["allow","deny","cancel","timeout"] as const;
export const TOOL_STATUS_VALUES = ["proposed","waitingApproval","running","succeeded","failed","cancelled","unknownOutcome"] as const;
export const ERROR_CODE_VALUES = ["RUNTIME_INVALID_ENVELOPE","RUNTIME_INVALID_SEQUENCE","RUNTIME_DUPLICATE_EVENT_CONFLICT","RUNTIME_UNSUPPORTED_PROTOCOL_MAJOR","RUNTIME_UNKNOWN_REQUIRED_EVENT","RUNTIME_INVALID_ENUM","RUNTIME_INTERNAL_ERROR","RUNTIME_PROVIDER_ERROR"] as const;

export type Id = string;

export interface ProtocolVersion {
  major: number;
  minor: number;
  patch: number;
}

export type Actor = "user" | "assistant" | "system" | "tool" | "runtime";

export type ApprovalDecision = "allow" | "deny" | "cancel" | "timeout";

export type ToolStatus = "proposed" | "waitingApproval" | "running" | "succeeded" | "failed" | "cancelled" | "unknownOutcome";

export type ErrorCode = "RUNTIME_INVALID_ENVELOPE" | "RUNTIME_INVALID_SEQUENCE" | "RUNTIME_DUPLICATE_EVENT_CONFLICT" | "RUNTIME_UNSUPPORTED_PROTOCOL_MAJOR" | "RUNTIME_UNKNOWN_REQUIRED_EVENT" | "RUNTIME_INVALID_ENUM" | "RUNTIME_INTERNAL_ERROR" | "RUNTIME_PROVIDER_ERROR";

export interface RuntimeError {
  code: ErrorCode;
  message: string;
  retryable?: boolean;
  details?: Record<string, unknown>;
}

export interface InitializeRequest {
  type: "initialize";
  clientVersion: string;
  supportedProtocolVersions: Array<ProtocolVersion>;
  capabilities: Array<string>;
}

export interface CapabilityNegotiationRequest {
  type: "capabilityNegotiation";
  capabilities: Array<string>;
}

export interface SessionListRequest {
  type: "sessionList";
}

export interface SessionCreateRequest {
  type: "sessionCreate";
  title?: string;
}

export interface SessionResumeRequest {
  type: "sessionResume";
  targetSessionId: Id;
}

export interface SessionCloseRequest {
  type: "sessionClose";
  targetSessionId: Id;
}

export interface SessionForkRequest {
  type: "sessionFork";
  targetSessionId: Id;
}

export interface PromptRequest {
  type: "prompt";
  content: string;
  stream: boolean;
}

export interface CancelRequest {
  type: "cancel";
  reason?: string;
}

export interface ApprovalRequest {
  type: "approval";
  approvalId: Id;
  decision: ApprovalDecision;
  reason?: string;
}

export interface MemoryRequest {
  type: "memory";
  operation: "query" | "put" | "delete";
  key?: string;
  value?: unknown;
}

export interface WorkspaceRequest {
  type: "workspace";
  operation: "open" | "read" | "write" | "list";
  path?: string;
  content?: string;
}

export interface UsageQueryRequest {
  type: "usageQuery";
  scope: "session" | "project" | "account";
}

export type RuntimeRequestPayload = InitializeRequest | CapabilityNegotiationRequest | SessionListRequest | SessionCreateRequest | SessionResumeRequest | SessionCloseRequest | SessionForkRequest | PromptRequest | CancelRequest | ApprovalRequest | MemoryRequest | WorkspaceRequest | UsageQueryRequest;

export interface ContentDeltaEvent {
  type: "contentDelta";
  delta: string;
}

export interface ToolProposedEvent {
  type: "toolProposed";
  toolCallId: Id;
  toolName: string;
  arguments: unknown;
}

export interface ToolStatusEvent {
  type: "toolStatus";
  toolCallId: Id;
  status: ToolStatus;
  message?: string;
}

export interface ToolResultEvent {
  type: "toolResult";
  toolCallId: Id;
  status: ToolStatus;
  result: unknown;
}

export interface ApprovalRequestedEvent {
  type: "approvalRequested";
  approvalId: Id;
  message: string;
  risk?: string;
}

export interface ApprovalResolvedEvent {
  type: "approvalResolved";
  approvalId: Id;
  decision: ApprovalDecision;
  reason?: string;
}

export interface CancelledEvent {
  type: "cancelled";
  reason?: string;
}

export interface ErrorEvent {
  type: "error";
  error: RuntimeError;
}

export interface MemoryContextEvent {
  type: "memoryContext";
  items: Array<unknown>;
}

export interface ContextCompressedEvent {
  type: "contextCompressed";
  beforeTokens: number;
  afterTokens: number;
}

export interface CheckpointEvent {
  type: "checkpoint";
  checkpointId: Id;
  label?: string;
}

export interface UsageEvent {
  type: "usage";
  inputTokens: number;
  outputTokens: number;
  costUsd?: number;
}

export interface FinishedEvent {
  type: "finished";
  reason: "complete" | "cancelled" | "error";
}

export type RuntimeEventPayload = ContentDeltaEvent | ToolProposedEvent | ToolStatusEvent | ToolResultEvent | ApprovalRequestedEvent | ApprovalResolvedEvent | CancelledEvent | ErrorEvent | MemoryContextEvent | ContextCompressedEvent | CheckpointEvent | UsageEvent | FinishedEvent;

export interface RuntimeRequestEnvelope {
  kind: "request";
  requestId: Id;
  sessionId: Id;
  turnId: Id;
  stepId: Id;
  traceId: Id;
  eventId: Id;
  sequence: number;
  timestamp: string;
  schemaVersion: "2.0.0";
  actor: Actor;
  payload: RuntimeRequestPayload;
}

export interface RuntimeEventEnvelope {
  kind: "event";
  requestId: Id;
  sessionId: Id;
  turnId: Id;
  stepId: Id;
  traceId: Id;
  eventId: Id;
  sequence: number;
  timestamp: string;
  schemaVersion: "2.0.0";
  actor: Actor;
  ignorable: boolean;
  payload: RuntimeEventPayload;
}

export interface RuntimeContractStatus {
  protocol: ProtocolVersion;
  schemaVersion: "2.0.0";
  v1AdapterUses: number;
}
