/**
 * @license Copyright 2026 ClawMaster SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from 'vitest';
import {
  ALL_AGENT_PROFILES,
  BASE_AGENT_PROFILES,
  COMMON_EXPERT_PROFILES,
  DEPARTMENT_AGENT_PROFILES,
  DEPARTMENT_IDS,
  ENTERPRISE_CEO_PROFILE,
  ENTERPRISE_WORK_PROFILE,
  PERSONAL_CLAWMASTER_PROFILE,
  SELF_DEVELOPMENT_PROFILE,
  getDepartmentAgentProfiles,
  getEnterpriseAgentProfiles,
  getPersonalAgentProfiles,
  setAutoGeneratedAgentProfiles,
} from './departmentAgents.js';

const COMMON_EXPERT_IDS = [
  'ppt',
  'meeting',
  'doc',
  'sheet',
  'pdf',
  'dataviz',
  'research',
  'copy',
];

describe('fixed Agent profile catalog', () => {
  it('keeps the fixed 9 Agents enterprise-only and personal mode on ClawMaster', () => {
    expect(getPersonalAgentProfiles().map((profile) => profile.id)).toEqual([
      'claw-personal',
    ]);

    const enterpriseCatalogs = [
      getEnterpriseAgentProfiles('company_owner'),
      getEnterpriseAgentProfiles('company_admin'),
      getEnterpriseAgentProfiles('manager'),
      getEnterpriseAgentProfiles('member', 'marketing'),
    ] as const;

    for (const profiles of enterpriseCatalogs) {
      expect(profiles.map((profile) => profile.id)).toEqual([
        'claw-enterprise-work',
        ...COMMON_EXPERT_IDS,
      ]);
      expect(profiles).toHaveLength(9);
    }

    expect(getPersonalAgentProfiles()).toEqual(BASE_AGENT_PROFILES);
    expect(COMMON_EXPERT_PROFILES).toHaveLength(8);
  });

  it('keeps the three server-whitelisted foundational profiles as independent objects', () => {
    expect(PERSONAL_CLAWMASTER_PROFILE).toMatchObject({
      id: 'claw-personal',
      name: 'ClawMaster',
      department: null,
    });
    expect(ENTERPRISE_CEO_PROFILE).toMatchObject({
      id: 'claw-enterprise-ceo',
      name: 'CEO Agent',
      department: null,
    });
    expect(ENTERPRISE_WORK_PROFILE).toMatchObject({
      id: 'claw-enterprise-work',
      scope: 'base',
      department: null,
    });
    expect(ENTERPRISE_WORK_PROFILE.systemPrompt).toContain(
      'enterprise_collaboration',
    );
    expect(ENTERPRISE_WORK_PROFILE.systemPrompt).toContain('先查询企业成员目录');
    expect(ENTERPRISE_WORK_PROFILE.systemPrompt).not.toContain(
      '不发起多 Agent 交流',
    );
    expect(PERSONAL_CLAWMASTER_PROFILE).not.toBe(ENTERPRISE_CEO_PROFILE);
    expect(PERSONAL_CLAWMASTER_PROFILE).not.toBe(ENTERPRISE_WORK_PROFILE);
    expect(ENTERPRISE_CEO_PROFILE).not.toBe(ENTERPRISE_WORK_PROFILE);

    expect(ALL_AGENT_PROFILES.map((profile) => profile.id)).toEqual([
      'claw-personal',
      'claw-enterprise-work',
      'self-development',
      ...COMMON_EXPERT_IDS,
    ]);
    expect(SELF_DEVELOPMENT_PROFILE.name).toBe('自主开发');
    expect(ALL_AGENT_PROFILES).toHaveLength(11);
  });

  it('keeps department Agents removed from the runtime catalog', () => {
    expect(DEPARTMENT_IDS).toHaveLength(0);
    expect(DEPARTMENT_AGENT_PROFILES).toHaveLength(0);
    expect(getDepartmentAgentProfiles('marketing')).toHaveLength(0);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.scope !== 'department')).toBe(true);
    expect(ALL_AGENT_PROFILES.every((profile) => profile.department === null)).toBe(true);
  });

  it('keeps auto-generated Skill profiles out of the fixed 9-Agent catalog', () => {
    setAutoGeneratedAgentProfiles([{
      id: 'auto-report',
      name: 'Auto Report',
      tagline: 'Generated profile',
      scope: 'base',
      department: null,
      skills: ['auto-report'],
      systemPrompt: 'Generated system prompt that should not enter the fixed catalog.',
    }]);

    expect(getPersonalAgentProfiles().map((profile) => profile.id)).toEqual(['claw-personal']);
    expect(getEnterpriseAgentProfiles('company_owner').map((profile) => profile.id)).toEqual([
      'claw-enterprise-work',
      ...COMMON_EXPERT_IDS,
    ]);
    expect(getEnterpriseAgentProfiles('member').map((profile) => profile.id)).toEqual([
      'claw-enterprise-work',
      ...COMMON_EXPERT_IDS,
    ]);
  });

  it('rejects generated profiles that collide with built-ins or have unsafe ids', () => {
    setAutoGeneratedAgentProfiles([
      {
        id: 'ppt',
        name: '覆盖内置专家',
        tagline: '',
        scope: 'personal',
        department: null,
        skills: [],
        systemPrompt: '不允许覆盖内置专家。',
      },
      {
        id: '../escape',
        name: '非法专家',
        tagline: '',
        scope: 'personal',
        department: null,
        skills: [],
        systemPrompt: '不允许非法 id。',
      },
    ]);

    expect(getPersonalAgentProfiles().map((profile) => profile.id)).toEqual(['claw-personal']);
  });

  it('keeps ids stable and system prompts private', () => {
    const ids = ALL_AGENT_PROFILES.map((profile) => profile.id);

    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z0-9-]+$/);
    for (const profile of ALL_AGENT_PROFILES) {
      expect(Array.isArray(profile.skills)).toBe(true);
      expect(profile.systemPrompt.trim().length).toBeGreaterThan(40);
      expect(profile).not.toHaveProperty('kickoff');
    }
  });
});
