/** Shared records and commands for the authenticated, local enterprise workspace. */
import type { Branded } from '@deepseek-ai/dsh-brand';

/** Identifier admitted by the enterprise wire parser. */
export type EnterpriseId = Branded<'ClawMasterEnterpriseId'>;

/**
 * Apply the compile-time brand; the Host validates incoming identifiers.
 * @param value Identifier generated by the client.
 * @returns The identifier with its enterprise record brand.
 */
export function enterpriseId(value: string): EnterpriseId { return value as EnterpriseId; }

/** CRM contact fields supplied by a user. Dates use YYYY-MM-DD or null. */
export interface ContactInput {
  id: EnterpriseId;
  name: string;
  company: string;
  stage: 'lead' | 'contacted' | 'proposal' | 'won' | 'lost';
  nextAction: string;
  nextActionDate: string | null;
}

/** Persisted contact with its most recent change time. */
export interface Contact extends ContactInput { updatedAt: string; }

/** Stock counts are nonnegative safe integers; changes are recorded in the audit log. */
export interface InventoryItemInput {
  id: EnterpriseId;
  sku: string;
  name: string;
  stock: number;
  reorderAt: number;
  supplier: string;
}

/** Persisted SKU with its most recent change time. */
export interface InventoryItem extends InventoryItemInput { updatedAt: string; }

/** One order line; money is an integer in the currency's minor unit. */
export interface OrderLine {
  itemId: EnterpriseId;
  quantity: number;
  unitPriceMinorUnits: number;
}

/** Editable purchase or sale order. Each SKU may occur only once. */
export interface OrderInput {
  id: EnterpriseId;
  kind: 'purchase' | 'sale';
  counterparty: string;
  orderDate: string;
  currency: 'CNY';
  lines: OrderLine[];
  note: string;
}

/** Submitted orders are immutable and their stock changes commit exactly once. */
export interface BusinessOrder extends OrderInput {
  status: 'draft' | 'submitted';
  totalMinorUnits: number;
  updatedAt: string;
  submittedAt: string | null;
}

/** One atomic business action; all mutations require the current snapshot revision. */
export type EnterpriseCommand =
  | { type: 'contact.upsert'; contact: ContactInput }
  | { type: 'contact.remove'; id: EnterpriseId }
  | { type: 'item.upsert'; item: InventoryItemInput }
  | { type: 'item.remove'; id: EnterpriseId }
  | { type: 'order.save'; order: OrderInput }
  | { type: 'order.remove'; id: EnterpriseId }
  | { type: 'order.submit'; id: EnterpriseId };

/** Retrying one commandId with the same command never repeats a mutation. */
export interface EnterpriseCommandRequest {
  generation: number;
  revision: number;
  commandId: EnterpriseId;
  command: EnterpriseCommand;
}

/** Durable before/after facts committed in the same transaction as the command. */
export interface AuditEntry {
  revision: number;
  commandId: EnterpriseId;
  type: EnterpriseCommand['type'];
  entityId: EnterpriseId;
  at: string;
  before: unknown;
  after: unknown;
}

/** Complete local business state, independent of browser origin and selected Session. */
export interface EnterpriseSnapshot {
  /** Database-local restore counter; never imported from a backup. */
  generation: number;
  revision: number;
  contacts: Contact[];
  inventory: InventoryItem[];
  orders: BusinessOrder[];
  audit: AuditEntry[];
}

/** Versioned collection selection; continuations require both database versions. */
export interface EnterpriseQuerySpec {
  collection: 'contacts' | 'inventory' | 'orders' | 'audit';
  id?: EnterpriseId;
  search?: string;
  stage?: ContactInput['stage'];
  dueBefore?: string;
  lowStock?: boolean;
  kind?: OrderInput['kind'];
  status?: BusinessOrder['status'];
  offset: number;
  limit: number;
  revision?: number;
  generation?: number;
}

/** One bounded collection page; absence here does not prove a record was deleted. */
export interface EnterpriseQueryPage {
  generation: number;
  revision: number;
  collection: EnterpriseQuerySpec['collection'];
  offset: number;
  total: number;
  nextOffset: number | null;
  records: Array<Contact | InventoryItem | BusinessOrder | AuditEntry>;
}

/** Counts and page limits at one database version, without business record bodies. */
export interface EnterpriseOverview {
  generation: number;
  revision: number;
  counts: { contacts: number; inventory: number; orders: number; audit: number; followups: number; lowStock: number };
  limits: { pageRows: number; pageBytes: number };
}

/** Durable acknowledgement independent of all other records and audit history. */
export interface EnterpriseCommandReceipt {
  generation: number;
  revision: number;
  commandId: EnterpriseId;
  commandRevision: number;
  entityId: EnterpriseId;
  type: EnterpriseCommand['type'];
  at: string;
}

/** Complete operator backup, including command receipts needed for idempotent restore. */
export interface EnterpriseBackup {
  schemaVersion: 1;
  exportedAt: string;
  snapshot: EnterpriseSnapshot;
  auditCommands: { revision: number; commandId: EnterpriseId; commandJson: string }[];
}

/** Stable failure codes consumed by the UI; messages contain no SQL or filesystem paths. */
export type EnterpriseErrorCode = 'invalid_request' | 'revision_conflict' | 'command_conflict'
  | 'not_found' | 'duplicate_sku' | 'referenced_item' | 'submitted_order'
  | 'insufficient_stock' | 'numeric_overflow' | 'storage_unavailable' | 'storage_invalid' | 'result_too_large';

/** Business failure with a stable client-safe code and optional current revision. */
export class EnterpriseError extends Error {
  readonly code: EnterpriseErrorCode;
  readonly currentRevision?: number;

  constructor(code: EnterpriseErrorCode, message: string, currentRevision?: number) {
    super(message);
    this.code = code;
    this.currentRevision = currentRevision;
    this.name = 'EnterpriseError';
  }
}

/** JSON error returned with an appropriate 4xx/5xx HTTP status. */
export interface EnterpriseErrorResponse {
  error: { code: EnterpriseErrorCode; message: string; currentRevision?: number };
}

/** Authenticated overview route; returns versions, counts and configured page limits. */
export const ENTERPRISE_SNAPSHOT_PATH = '/api/clawmaster/enterprise';
/** Authenticated bounded single-collection query route. */
export const ENTERPRISE_QUERY_PATH = '/api/clawmaster/enterprise/query';
/** Authenticated route returning a restore-capable backup envelope. */
export const ENTERPRISE_BACKUP_PATH = '/api/clawmaster/enterprise/backup';
/** Authenticated route for an explicitly confirmed atomic restore. */
export const ENTERPRISE_RESTORE_PATH = '/api/clawmaster/enterprise/restore';
/** Authenticated command route; successful responses contain only the durable receipt. */
export const ENTERPRISE_COMMAND_PATH = '/api/clawmaster/enterprise/command';
